# Generated by Django 4.2.13 on 2024-05-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
    ]
